[2025-10-27T17:47:05.574+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T17:47:05.589+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:05.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:05.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T17:47:05.602+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-10-27 16:00:00+00:00
[2025-10-27T17:47:05.607+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T17:47:05.608+0000] {standard_task_runner.py:64} INFO - Started process 78 to run task
[2025-10-27T17:47:05.609+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'transform_data', 'scheduled__2025-10-27T16:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpj7vrrxnr']
[2025-10-27T17:47:05.610+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask transform_data
[2025-10-27T17:47:05.642+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.transform_data scheduled__2025-10-27T16:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T17:47:05.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T16:00:00+00:00'
[2025-10-27T17:47:05.704+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T17:47:05.751+0000] {mysql_to_postgres_etl.py:167} INFO - Transformed data: 66 rows ready for loading
[2025-10-27T17:47:05.765+0000] {python.py:237} INFO - Done. Returned value was:     receipt_id  customer_id  ...           deleted_at             etl_updated_at
0        51669         1086  ...                 None 2025-10-27 17:47:05.750117
1         8681         2964  ...                 None 2025-10-27 17:47:05.750117
2        81639          403  ...  2025-10-27 15:01:39 2025-10-27 17:47:05.750117
3        20276         3994  ...                 None 2025-10-27 17:47:05.750117
4        78585         2000  ...  2025-10-27 15:02:41 2025-10-27 17:47:05.750117
..         ...          ...  ...                  ...                        ...
61       69171          315  ...                 None 2025-10-27 17:47:05.750117
62       89092         1319  ...                 None 2025-10-27 17:47:05.750117
63       63975         3081  ...                 None 2025-10-27 17:47:05.750117
64       63293         3717  ...                 None 2025-10-27 17:47:05.750117
65        4659          860  ...  2025-10-27 15:58:08 2025-10-27 17:47:05.750117

[66 rows x 9 columns]
[2025-10-27T17:47:05.783+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T17:47:05.799+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=transform_data, run_id=scheduled__2025-10-27T16:00:00+00:00, execution_date=20251027T160000, start_date=20251027T174705, end_date=20251027T174705
[2025-10-27T17:47:05.829+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T17:47:05.849+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T17:47:05.850+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
