[2025-10-27T15:43:07.385+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:43:07.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:42:59.687694+00:00 [queued]>
[2025-10-27T15:43:07.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:42:59.687694+00:00 [queued]>
[2025-10-27T15:43:07.409+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:43:07.418+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-10-27 15:42:59.687694+00:00
[2025-10-27T15:43:07.423+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=684) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:43:07.424+0000] {standard_task_runner.py:64} INFO - Started process 686 to run task
[2025-10-27T15:43:07.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'transform_data', 'manual__2025-10-27T15:42:59.687694+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmp_mplnp8f']
[2025-10-27T15:43:07.426+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask transform_data
[2025-10-27T15:43:07.458+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:42:59.687694+00:00 [running]> on host a0076f556b70
[2025-10-27T15:43:07.528+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:42:59.687694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:42:59.687694+00:00'
[2025-10-27T15:43:07.529+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:43:07.638+0000] {mysql_to_postgres_etl.py:154} INFO - Transformed data: 52227 rows ready for loading
[2025-10-27T15:43:07.870+0000] {python.py:237} INFO - Done. Returned value was:        receipt_id  customer_id  ...           deleted_at             etl_updated_at
0           93579         1085  ...                 None 2025-10-27 15:43:07.629157
1           45036         3915  ...                 None 2025-10-27 15:43:07.629157
2           25341         2036  ...                 None 2025-10-27 15:43:07.629157
3           95344         4341  ...                 None 2025-10-27 15:43:07.629157
4              96         4303  ...  2025-10-27 14:50:06 2025-10-27 15:43:07.629157
...           ...          ...  ...                  ...                        ...
52222       25267         3556  ...                 None 2025-10-27 15:43:07.629157
52223       72729         4833  ...                 None 2025-10-27 15:43:07.629157
52224        5867         1554  ...                 None 2025-10-27 15:43:07.629157
52225       61480         4665  ...  2025-11-29 19:06:22 2025-10-27 15:43:07.629157
52226       47452          694  ...                 None 2025-10-27 15:43:07.629157

[52227 rows x 9 columns]
[2025-10-27T15:43:07.890+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:43:08.320+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=transform_data, run_id=manual__2025-10-27T15:42:59.687694+00:00, execution_date=20251027T154259, start_date=20251027T154307, end_date=20251027T154308
[2025-10-27T15:43:08.383+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:43:08.424+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:43:08.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
