[2025-10-27T17:47:03.497+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T17:47:03.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.extract_from_mysql scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:03.519+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.extract_from_mysql scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:03.519+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T17:47:03.530+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2025-10-27 16:00:00+00:00
[2025-10-27T17:47:03.535+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T17:47:03.536+0000] {standard_task_runner.py:64} INFO - Started process 75 to run task
[2025-10-27T17:47:03.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'extract_from_mysql', 'scheduled__2025-10-27T16:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpj3fjnel5']
[2025-10-27T17:47:03.538+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask extract_from_mysql
[2025-10-27T17:47:03.586+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.extract_from_mysql scheduled__2025-10-27T16:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T17:47:03.666+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T16:00:00+00:00'
[2025-10-27T17:47:03.668+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T17:47:03.668+0000] {mysql_to_postgres_etl.py:90} INFO - Extracting data for time window: 2025-10-27 15:00:00+00:00 to 2025-10-27 16:00:00+00:00
[2025-10-27T17:47:03.675+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T17:47:03.686+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-10-27T17:47:03.745+0000] {mysql_to_postgres_etl.py:120} INFO - Extracted 66 rows from MySQL for window: 2025-10-27 15:00:00+00:00 to 2025-10-27 16:00:00+00:00
[2025-10-27T17:47:03.748+0000] {mysql_to_postgres_etl.py:126} INFO - Status distribution in extracted data:
[2025-10-27T17:47:03.749+0000] {mysql_to_postgres_etl.py:128} INFO - - delivered: 19 records
[2025-10-27T17:47:03.749+0000] {mysql_to_postgres_etl.py:128} INFO - - in_transit: 16 records
[2025-10-27T17:47:03.749+0000] {mysql_to_postgres_etl.py:128} INFO - - done: 16 records
[2025-10-27T17:47:03.749+0000] {mysql_to_postgres_etl.py:128} INFO - - created: 15 records
[2025-10-27T17:47:03.795+0000] {python.py:237} INFO - Done. Returned value was:     receipt_id  customer_id  ...          updated_at          deleted_at
0        51669         1086  ... 2025-10-27 15:00:08                 NaT
1         8681         2964  ... 2025-10-27 15:00:13                 NaT
2        81639          403  ... 2025-10-27 15:01:39 2025-10-27 15:01:39
3        20276         3994  ... 2025-10-27 15:01:47                 NaT
4        78585         2000  ... 2025-10-27 15:02:41 2025-10-27 15:02:41
..         ...          ...  ...                 ...                 ...
61       69171          315  ... 2025-10-27 15:56:19                 NaT
62       89092         1319  ... 2025-10-27 15:57:47                 NaT
63       63975         3081  ... 2025-10-27 15:57:56                 NaT
64       63293         3717  ... 2025-10-27 15:58:08                 NaT
65        4659          860  ... 2025-10-27 15:58:08 2025-10-27 15:58:08

[66 rows x 8 columns]
[2025-10-27T17:47:03.817+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T17:47:03.840+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=extract_from_mysql, run_id=scheduled__2025-10-27T16:00:00+00:00, execution_date=20251027T160000, start_date=20251027T174703, end_date=20251027T174703
[2025-10-27T17:47:03.881+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T17:47:03.902+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T17:47:03.904+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
