[2025-10-27T15:33:35.194+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:33:35.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:33:29.332998+00:00 [queued]>
[2025-10-27T15:33:35.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:33:29.332998+00:00 [queued]>
[2025-10-27T15:33:35.220+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:33:35.231+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-10-27 15:33:29.332998+00:00
[2025-10-27T15:33:35.238+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=505) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:33:35.241+0000] {standard_task_runner.py:64} INFO - Started process 507 to run task
[2025-10-27T15:33:35.240+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'transform_data', 'manual__2025-10-27T15:33:29.332998+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpxsfm3iwg']
[2025-10-27T15:33:35.241+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask transform_data
[2025-10-27T15:33:35.274+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:33:29.332998+00:00 [running]> on host a0076f556b70
[2025-10-27T15:33:35.345+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:33:29.332998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:33:29.332998+00:00'
[2025-10-27T15:33:35.346+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:33:35.387+0000] {mysql_to_postgres_etl.py:161} INFO - Transformed data: 1000 rows ready for loading
[2025-10-27T15:33:35.414+0000] {python.py:237} INFO - Done. Returned value was:      receipt_id  customer_id  ... deleted_at             etl_updated_at
0         38908         4362  ...       None 2025-10-27 15:33:35.386716
1         20530         2716  ...       None 2025-10-27 15:33:35.386716
2         78906         4284  ...       None 2025-10-27 15:33:35.386716
3         98325         2236  ...       None 2025-10-27 15:33:35.386716
4         57976         2358  ...       None 2025-10-27 15:33:35.386716
..          ...          ...  ...        ...                        ...
995       98184         2175  ...       None 2025-10-27 15:33:35.386716
996       85934         3903  ...       None 2025-10-27 15:33:35.386716
997       45277         2053  ...       None 2025-10-27 15:33:35.386716
998       44397         4100  ...       None 2025-10-27 15:33:35.386716
999       36244         2344  ...       None 2025-10-27 15:33:35.386716

[1000 rows x 9 columns]
[2025-10-27T15:33:35.434+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:33:35.461+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=transform_data, run_id=manual__2025-10-27T15:33:29.332998+00:00, execution_date=20251027T153329, start_date=20251027T153335, end_date=20251027T153335
[2025-10-27T15:33:35.503+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:33:35.527+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:33:35.529+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
